version: '3.8'


services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD={DB_PASSWORD}
      - MSSQL_PID=Express
    command: /bin/bash -c /bin/bash /usr/src/app/entrypoint.sh && /opt/mssql/bin/sqlservr 
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
